pgdata:
  image: "tianon/true"
  volumes:
  - /var/lib/postgresql/data
cache:
  image: "tianon/true"
  volumes:
  - /data/cache
postgres:
  build: "src/postgres"
  mem_limit: 500000000
  volumes_from:
   - pgdata
  ports:
   - "5432"
import-osm:
  build: "src/import-osm"
  command: ./import-osm.sh
  volumes:
   - ./data:/data/import
  volumes_from:
   - cache
  links:
   - postgres:postgres
mapbox-studio:
  build: "src/mapbox-studio"
  mem_limit: 500000000
  volumes:
   - ./src/vector-datasource:/projects/vector-datasource.tm2source
  links:
   - postgres:postgres
  ports:
   - "3000:3000"
export-vectortiles:
  build: "src/export-vectortiles"
  volumes:
   - ./data:/data/export
   - ./src/vector-datasource:/data/tm2source
  links:
   - postgres:db
  environment:
    BBOX: "5.8559113 45.717995 10.5922941 47.9084648"
    MIN_ZOOM: "10"
    MAX_ZOOM: "10"
serve-vectortiles:
  image: "klokantech/tileserver-php"
  volumes:
   - ./data:/var/www
  ports:
   - "8080:80"
